### ISSUE TITLE
How about adding switching off SMT as part of build script

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/builds#16]
SMT can be switched off as part to build script? as it is certainly expected to have it off for turning host into powerkvm mode.

**Comment by maurorodrigues** [comment]
Hi @sathnaga thank you for the suggestion! There are some 'design decisions' made here, like we could install dependencies necessary to run the scripts but we prefer not to, same applies to SMT. Because, for instance, the user may build the packages in a machine to install in all his other machines too, omitting the manual step of setting SMT to Off by turning it implicit in the build scripts would cloud the user's attention to do turn it off in all his machines.

In order to get that fixed we're gathering packages related to configurations and we'll add support to build them too so such settings will be applied through the packages installed. For SMT for instance there is a init script that will set it to off during system boot.

The bug will be kept open til we got that package available.

**Comment by olavphibm** [comment]
Like Mauro explained, disabling SMT is not required for building packages, but is desired when installing Host OS packages to prepare the system for virtualization. This is configured when the `open-power-host-os-release` package is installed, and was implemented in https://github.com/open-power-host-os/versions/pull/142.
