### ISSUE TITLE
Power8: Kickstart installation fails with "More than one match found for given boot drive "disk/by-id/scsi-1IBM_IPR-0_5EDF3D0000000020""

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/builds#298]
Iso: Host_OS-DVD-ppc64le-20170922T220252.iso
```
tarting installer, one moment...
anaconda 21.48.22.121-1 for Host_OS 20170922T220252 started.
 * installation log files are stored in /tmp during the installation
 * shell is available on TTY2
 * when reporting a bug add logs from /tmp as separate text/plain attachments
12:41:54 Not asking for VNC because of an automated install
12:41:54 Not asking for VNC because text mode was explicitly asked for in kickstart

Starting automated install...
Checking software selection
Generating updated storage configuration
104)
12:41:58,727 INFO anaconda: Thread Done: AnaSourceWatcher (140735713898928)
12:42:00,380 INFO anaconda: Thread Done: AnaCheckSoftwareThread (140735688733104)
12:42:00,380 INFO anaconda: Module initialized: SoftwareSpoke
12:42:00,380 INFO anaconda: All modules have been initialized.
12:42:00,380 INFO anaconda: Thread Done: AnaSoftwareWatcher (140735697121712)
12:42:02,661 DEBUG anaconda: new disk order: []
12:42:02,732 DEBUG anaconda: disk/by-id/scsi-1IBM_IPR-0_5EDF3D0000000020 matches [u'sdb', u'sdd'] for devicetree=<blivet.devicetree.DeviceTree object at 0x7fff9d6e79d0> and disks_only=True
12:42:02,733 ERR anaconda: storage configuration failed: The following problem occurred on line 12 of the kickstart file:

More than one match found for given boot drive "disk/by-id/scsi-1IBM_IPR-0_5EDF3D0000000020".

12:42:04,565 DEBUG anaconda: Entered hub: SummaryHub
12:42:04,664 INFO anaconda: fs space: 0 B  needed: 1369.42 MiB
12:42:04,681 ERR anaconda: Not enough space in file systems for the current software selection. An additional 1369.42 MiB is needed.
12:42:04,682 INFO anaconda: Running Thread: AnaInputThread1 (140735697121712)

[anaconda] 1:main- 2:shell  3:log* 4:storage-lo> Switch tab: Alt+Tab | Help: F1 
Not enough space in file systems for the current software selection. An additional 1369.42 MiB is needed.
Enter 'b' to ignore the warning and attempt to install anyway.
  Please make your choice from above ['q' to quit | 'b' to begin installation |
  'r' to refresh]: 

```

<cde:info> Mirrored with LTC bug #159192 </cde:info>

**Comment by sathnaga** [comment]
kickstart file used:
```
%pre
%end
url --url=http://9.40.192.92:81/sath/hostos3.0/sprint1/iso/
text
keyboard --vckeymap=us --xlayouts='us'
services --enabled=NetworkManager,sshd
lang en_US.UTF-8
rootpw passw0rd
skipx
timezone Asia/Kolkata --isUtc
ignoredisk --only-use=disk/by-id/scsi-1IBM_IPR-0_5EDF3D0000000020
bootloader  --location=mbr  --append="console=tty0" --timeout=1 --boot-drive=disk/by-id/scsi-1IBM_IPR-0_5EDF3D0000000020
zerombr
clearpart --all --initlabel  --drives=disk/by-id/scsi-1IBM_IPR-0_5EDF3D0000000020
autopart --type=lvm --fstype=ext4
reboot
%packages --ignoremissing
@core

%end
%post
%end
```

**Comment by cdeadmin** [comment]
------- Comment (attachment only) From satheera@in.ibm.com 2017-09-25 09:24:51 EDT-------

**Comment by cdeadmin** [comment]
------- Comment (attachment only) From satheera@in.ibm.com 2017-09-25 10:21:57 EDT-------

**Comment by cdeadmin** [comment]
------- Comment From jamesspo@us.ibm.com 2017-09-27 10:42:15 EDT-------
There's a bug here in the RHEL installer, but we'll defer to a later sprint (leaving targeted at Future for now).

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-02-15 00:35:34 EDT-------
Is there *really* a bug we're going after here? Dropping from ship to normal severity, in any case.

**Comment by cdeadmin** [comment]
------- Comment From muriloo@br.ibm.com 2018-02-16 09:25:31 EDT-------
(In reply to comment #9)
&gt; Is there *really* a bug we're going after here? Dropping from ship to normal
&gt; severity, in any case.

Hi, Scott.

Reading Red Hat's documentation [0] about persistent naming of storage devices, there is no statement whether we should prefer the multipath name (e.g.: disk/by-id/dm-uuid-mpath-1IBM_IPR-0_5EDF3D0000000020) over one of its path names (e.g.: disk/by-id/scsi-1IBM_IPR-0_5EDF3D0000000020).

Perhaps this is not even a bug and RHEL installer is working as designed. In this case, I believe documentation should be more explicit to select multipath name over one of its paths during installations. Perhaps that's already stated somewhere in RHEL docs and I'm not aware of.

It's up to Red Hat to decide what to do with bug https://bugzilla.redhat.com/show_bug.cgi?id=1497841.

I agree this is not a ship issue because there is a workaround that can be used.

Cheers
Murilo

[0] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/persistent_naming
