### ISSUE TITLE
Weekly build version to be updated in a file( /etc/ibm-release)

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/builds#42]
It would be good to have information of weekly build in a release file in etc directory, for e.x /etc/ibm-release
to keep user updated with what weekly build he/she currently in.

Thanks in advance.

**Comment by maurorodrigues** [comment]
Hi @sathnaga I was talking to @rmatinata-ibm trying to get some ideas and we agreed that this is not the correct approach to identify which weekly build we're working with cause we don't release we delivery continuously so a release file would against this idea.

I'm working with two ideas here, one is to use createrepo --revision some_string, which includes a revision field on the repomd.xml file.
The other is to make our repository installable like epel is and thus to know the current version you're playing with it would be just a matter of typing yum info <name-of-our-repo-rpm> and see the version.

I'm planning this for September 14th for now.

**Comment by maurorodrigues** [comment]
how repomd.xml looks like with revision option.
```
[user@jaspion1 builds]$ cat ~/repositorio/repodata/repomd.xml
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
 <revision>ttt-rev-str</revision>
```

**Comment by maurorodrigues** [comment]
references to revision field at yum code that may help us to get such info from it: https://github.com/rpm-software-management/yum/blob/a9e13b6277eade8d1d5f8e72ba82bfee746f2eec/yum/repoMDObject.py

**Comment by olavphibm** [comment]
We could mark the release version in each package built

**Comment by maurorodrigues** [comment]
Yes, we could (and we did it a couple of times in the first pair of builds) but that would mean the package with new release would be available for upgrade and thus for testing.

The objective here is to avoid duplicate the efforts from test team, kernel for instance hasn't change in the last 2 weeks, if we increase release tag the test team can't figure out if they should test or not, unless some human being look into the weekly build Pull Request ( aka we need to flag this somewhere that doesn't interfere with the package upgradeability in order to get it parsed by some automation in Test team's CI)

**Comment by olavphibm** [comment]
We now have a spec for the `open-power-host-os-release` package (https://github.com/open-power-host-os/versions/blob/master/open-power-host-os/CentOS/7/open-power-host-os.spec).
When it is installed, it places a file at `/etc/open-power-host-os-release` indicating the current OpenPOWER Host OS version, as described in https://github.com/open-power-host-os/versions/blob/master/README.md#release-package.
