### ISSUE TITLE
host-os-build.py crashes and throws exception when changing build version 

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#54]
**How to reproduce**
Given for instance current versions master, which contains versions for sos, and a version tag which doesn't (none in special, just removed sos, committed tagged and used it as build version).

```
[user@jaspion1 builds]$ python host-os-build.py --package sos --build-version another
Logs available at /var/log/host-os/builds.log
Traceback (most recent call last):
  File "host-os-build.py", line 100, in <module>
    sys.exit(main(sys.argv[1:]))
  File "host-os-build.py", line 92, in main
    return build_manager()
  File "/home/user/dev/builds/lib/manager.py", line 43, in __call__
    self.packages = self._prepare_packages()
  File "/home/user/dev/builds/lib/manager.py", line 76, in _prepare_packages
    self.packages_list)]
  File "/home/user/dev/builds/lib/package.py", line 51, in __init__
    self.load_package(package, distro)
  File "/home/user/dev/builds/lib/package.py", line 68, in load_package
    with open(self.package_file, 'r') as package_file:
IOError: [Errno 2] No such file or directory: '/home/user/dev/builds/components/sos/sos.yaml'
```

This happens cause when host-os-build.py start it had sos directory, but then it checks out into the selected build version which removes it and things blow up.

**Comment by fabianorosas** [comment]
Just to clarify, there are two issues happening here:

1. Issuing `python host-os-build.py --package inexistent_package`, which breaks because there are no files for the listed package.

1. Running the script without the `--packages` option, which causes early discovery of packages and is susceptible to reading from a branch which will later be changed.

The fix for 1) is simple exception handling and for 2) I think we should just delay the discovery of packages until after the proper branch is checked-out.

I'll update #91 to address these two issues correctly.
