### ISSUE TITLE
Include build dependencies in the result directory

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/builds#87]
Build dependencies, [gcc](https://github.com/open-power-host-os/versions/tree/master/build_dependencies/gcc) and [librtas](https://github.com/open-power-host-os/versions/tree/master/build_dependencies/librtas), should also be placed in the `result` directory and delivered as output of the `host-os-build.py` script.

That way, users will be able, for example, to build a custom kernel with the same gcc package used to build kernel package generated by `host-os-build.py`.

**Comment by fabianorosas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Include build dependencies in the result directory](https://trello.com/c/lbIkvdll/34-deliver-build-dependencies-as-a-result-of-host-os-build-py)

**Comment by maurorodrigues** [comment]
For such task the workflow is to make his changes in versions (adding a patch, cloning a different kernel, etc), commit it, tag and trigger a build with --build-version my_tag_in_versions.

I do agree with this for two other reasons though, the project's direction seems to be changing to delivery more and more packages, be it the missing ones or newer versions, at least until we get them in epel or centos's extras repo, so eventually librtas and others will be required; for gcc specifically needs to be delivered in order to build the modules that an user wants to patch in kernel (we do have live patch enabled in kernel but CentOS's gcc can't compile modules that we want to patch into the kernel as per Ricardo).

So LGTM but let's also create a task to do a code cleanup to remove it completely (not exactly a revert, but remove most of what this commit https://github.com/open-power-host-os/builds/commit/e92e615549be424965e58861e02072890386be83 added)b

**Comment by maurorodrigues** [comment]
@mopsfelder can you open a PR please?

**Comment by mopsfelder** [comment]
@maurorodrigues I have submitted pull #88.
