### ISSUE TITLE
Environment setup does not create user home directory

### ISSUE THREAD

**Issue by fabianorosas** [open-power-host-os/builds#98]
The `setup-environment.py` script does not create the home directory when the user doesn't exist. Since the user will inevitably have to create this directory manually, I think the script should do it instead.

**Comment by maurorodrigues** [comment]
well, the idea was if the user (meaning the person) using the scripts could want a dedicated user to run the scripts. The home directory isn't really a requirement. It's an enhancement though, could be an option during that step.

There are several other improvements to the script though (like allowing the new user to execute the build scripts in the current path, set the permissions for the group instead of user's, and so on)

**Comment by fabianorosas** [comment]
Just to make sure I we're on the same page, what I was thinking was more aligned with the improvements you listed because even if the person wants a dedicated user to run the script, the permissions would still be wrong and they would have to "chmod" everything or log into the account and clone the repo, hence the home directory.

I think having some permission-related options is a better approach than simply creating the home directory though.

**Comment by olavphibm** [comment]
I think setting the permission of the current script path to the user would suffice.

**Comment by mopsfelder** [comment]
Have we agreed on the following approach?

- If user does not exist
  - create user
  - create home directory
- Add user to the group mock
- Give directories read/write permissions for the group mock

**Comment by fabianorosas** [comment]
PR #191 invalidates this issue by removing the `set-env` command.
